name: Generar Binarios Ultra Facil

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm install -g pkg
    - run: npm install

    - name: Compilar pentru Windows (EXE)
      run: pkg . --targets node20-win-x64 --output infinitycommerce.exe

    - name: Urca EXE pentru download
      uses: actions/upload-artifact@v4
      with:
        name: infinitycommerce-exe
        path: infinitycommerce.exe
